server:
  port: 0
spring:
  application:
    name: auth-service
  config:
   import: optional:configserver:http://localhost:8811
  cloud:
   config:
     name: mapConfig
     profile: default, token
   bus:
     enabled: true
     refresh:
       enabled: true
  kafka:
    bootstrap-servers: http://localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: busrefresh, info, metrics, prometheus
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka



