server:
  port: 0
spring:
  thymeleaf:
    enabled : true
    prefix: classpath:templates/
    suffix: .html
  application:
    name: map-service
  config:
    import: optional:configserver:http:/localhost:8811
  cloud:
    config:
      name: mapConfig
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka